### ISSUE TITLE
type 'button' だとポストにリクエストが飛ばなかったので編集した

### ISSUE THREAD

**Issue by kevin3314** [shortintern2020-B-frontier/TeamF#16]
この部分を 'button' -> 'submit' に変えてしまったので、うまいことやりたい
https://github.com/shortintern2020-B-frontier/TeamF/blob/ffd32013672dc3264ca241e21337941d7f1322ca/mysite/posts/templates/posts/create.html#L52

**Comment by pepepor123** [comment]
遅くなりましたがOKです
